### ISSUE TITLE
如果 json 内存在空的 object，则会多显示一个 "}"

### ISSUE THREAD

**Issue by BlodSide** [zhaoxuhui1122/vue-json-view#1]
如果 json 数据中存在空的 object，则会多显示一个 "}"。如下图所示
![image](https://user-images.githubusercontent.com/10192432/62681443-460a2080-b9ec-11e9-9e72-c7454f912072.png)

**Comment by zhaoxuhui1122** [comment]
最新版已修复，判断数据类型有遗漏
