### ISSUE TITLE
json-key过长时会导致json-value换行

### ISSUE THREAD

**Issue by Jasery** [zhaoxuhui1122/vue-json-view#4]
json-key过长时会导致json-value换行，估计是`.json-item`的`display`设置为`flex`引起的
![bug](https://user-images.githubusercontent.com/20091279/76920512-9c3a2d00-6906-11ea-988b-3bdf6119c922.png)

**Comment by zhaoxuhui1122** [comment]
已修复，过长时会不会换行，左右整体滚动，如果需要换行，可自行修改样式，搜索【.json-value】
